version: '3.8'

services:
  server:
    build:
      context: .
    environment:
      MYSQL_HOST: host.docker.internal
      MYSQL_PORT: 3317
      MYSQL_DATABASE: workshop_vehicles_db
      MYSQL_USER: root
      MYSQL_PASSWORD: hfr6Y-34ApW-sP14J
      AUTH_VALIDATE_TOKEN_API_URL: http://host.docker.internal:8083/api/v1/auth/validate
      EUREKA_SERVER_URI: http://host.docker.internal:8761/eureka
      ZIPKIN_SERVER_URI: http://host.docker.internal:9411
      RABBIT_SERVER_URI: amqp://guest:guest@rabbitmq:5672
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_ZIPKIN_SENDER_TYPE: rabbit
      SERVER_PORT: 8082
    ports:
        - "8082:8082"
    networks:
      - workshop_network
networks:
  workshop_network: