server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URI:http://localhost:8761/eureka}
auth:
  validateTokenApiUrl: ${AUTH_VALIDATE_TOKEN_API_URL:/api/v1/auth/validate}
spring:
  application:
    name: workshop-vehicles-api
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3317}/${MYSQL_DATABASE:workshop_vehicles_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:hfr6Y-34ApW-sP14J}
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update
        format_sql: true
        enable_lazy_load_no_trans: true
        jdbc:
          lob:
            non_contextual_creation: true
        c3p0:
          min_size: 5
          max_size: 20
          timeout: 300
          max_statements: 50
          idle_test_period: 3000
          acquire_increment: 5
          validate: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: org.hibernate.dialect.MySQLDialect
  cloud:
    compatibility-verifier:
      enabled: false
logging:
  level:
    org:
      springframework:
        security: DEBUG